image: alpine/edge
packages:
    - git
secrets:
    - 78f39fb6-1185-492f-9c21-f755e10b5e5d # ssh key for mirroring
environment:
    GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
    - nopr: |
        # Don't run on GitHub PRs
        [ "$BUILD_SUBMITTER" = 'git.sr.ht' ] || complete-build
    - mirror: |
        cd fzy.zig
        git push --force --mirror git@github.com:gpanders/fzy.zig
